### ISSUE TITLE
Script breaks with UnicodeEncodeError submitting to time logger if unicode found in toggl description

### ISSUE THREAD

**Issue by Nick-OpusVL** [PeterAlabaster/toggl-export-import#6]
Note this could have come from my own patches - I haven't tested against the original by @PeterAlabaster 

Here's the output:

```
$ ./run.py yest
{1: {'contract': u'OpusVL - General Admin',
     'date': u'2017-11-16',
     'description': u'General email/planning/discussion',
     'duration': 4288}}
{1: {'contract': u'OurCustomer - Support 2017',
     'date': u'2017-11-16',
     'description': u'[T424242]\xa0Find out where these requests come from in OurCustomersApp',
     'duration': 5712}}
Traceback (most recent call last):
  File "./run.py", line 23, in <module>
    run()
  File "./run.py", line 21, in run
    timeloggerimport.import_data(togglexport.export(date))
  File "/home/nick.booker/src/toggl-export-import/timeloggerimport.py", line 47, in import_data
    log_time_for_group(dt, contract, desc, [l.values()[0] for l in lines])
  File "/home/nick.booker/src/toggl-export-import/timeloggerimport.py", line 58, in log_time_for_group
    log_line(logging_line)
  File "/home/nick.booker/src/toggl-export-import/timeloggerimport.py", line 94, in log_line
    br.submit()
  File "/home/nick.booker/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 683, in submit
    return self.open(self.click(*args, **kwds))
  File "/home/nick.booker/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 673, in click
    request = self.form.click(*args, **kwds)
  File "/home/nick.booker/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 2238, in click
    self._request_class)
  File "/home/nick.booker/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 2456, in _click
    return control._click(self, coord, return_type, request_class)
  File "/home/nick.booker/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 1505, in _click
    r = form._switch_click(return_type, request_class)
  File "/home/nick.booker/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 2525, in _switch_click
    req_data = self._request_data()
  File "/home/nick.booker/.local/lib/python2.7/site-packages/mechanize/_form_controls.py", line 2499, in _request_data
    return (uri, urllib.urlencode(self._pairs()),
  File "/usr/lib/python2.7/urllib.py", line 1343, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 8: ordinal not in range(128)
```

**Comment by Nick-OpusVL** [comment]
I guess I copy-pasted in a non-breaking space somehow.

https://en.wikipedia.org/wiki/Non-breaking_space
